spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/demodept?characterEncoding=UTF-8
    username: root
    password: lixf
    driver-class-name: com.mysql.jdbc.Driver



management:
  endpoints:
    web:
      exposure:
        include: beans,metrics,health
  endpoint:
    health:
      show-details: always