
server:
  port: 8764

spring:
  application:
    name: service-dept
  profiles:
    active: dev
  cloud:
    consul:
      #consul地址
      host: localhost
      #consul 对外提供服务的端口
      port: 8500
      discovery:
        #服务提供者对外提供的健康检查接口,使用了actuator
#        healthCheckPath: /actuator/health


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

#swagger 配置
swagger:
  title: 部门服务API
  desc: 基于springBoot编写的RESful-API
  version: 0.0.1.SNAPSHOT
  termsOfServiceUrl: javascript:void(0)
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  basePackage: com.example.microservices.servicedept.controller
  contactName: chengqp
  contactUrl:
  contactEmail: chengqianpeng@resoft.css.com.cn
