
server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: service-dept
          uri: lb://service-dept
          predicates:
            - Path=/api/depts/**
          filters:
            - StripPrefix=2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


