spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/demouser?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#spring:
#  main:
#    allow-bean-definition-overriding: true
#
#sharding:
#  jdbc:
#    datasource:
#      names: ds0
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/demouser?characterEncoding=UTF-8
#        username: root
#        password: 123456
#
#    config:
#      sharding:
#        tables:
#          org_user:
#            actual-data-nodes: ds0.org_user_$->{0..2}
#            table-strategy:
#              inline:
#                sharding-column: user_id
#                algorithm-expression: org_user_$->{user_id % 3}
#              key-generator-column-name: user_id
#        props:
#          sql:
#            show: true

logging:
  level:
    com.example.microserives.serviceuser.dao.mapper: debug

management:
  endpoints:
    web:
      exposure:
        include: beans,metrics,health
  endpoint:
    health:
      show-details: always